application: oppiaserver
version: 2
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /images
  static_dir: static/images
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /css
  static_dir: static/css
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /img
  static_dir: third_party/bootstrap/img
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /third_party/static
  static_dir: third_party/static
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /data/widgets/(.*)/static/(.*)
  static_files: data/widgets/\1/static/\2
  upload: data/widgets/(.*)/static/(.*)
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: '2.6'
- name: webapp2
  version: '2.5.2'

env_variables:
  DJANGO_SETTINGS_MODULE: 'oppia-test-server.settings'
