application: oppiaserver
version: 2
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
- url: /third_party/postmessage/postmessage.js
  static_files: third_party/postmessage/postmessage.js
  upload: third_party/postmessage/postmessage.js
  secure: always
- url: /images
  static_dir: static/images
  secure: always
- url: /img
  static_dir: third_party/bootstrap/img
  secure: always
- url: /data/widgets/(.*)/static/(.*)
  static_files: data/widgets/\1/static/\2
  upload: data/widgets/(.*)/static/(.*)
  secure: always
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'oppia-test-server.settings'
