# The system name for this widget.
id: NumericInput

# The human-readable name of the widget.
name: Numeric input
# The category the widget falls under in the widget repository.
category: Interactive
# A description of the widget.
description: |
  A numeric input widget that can accept and classify integers and
  floating point numbers.

# Actions that the reader can perform on this widget which trigger a feedback
# interaction.
actions:
  submit:
    classifier: NumericClassifier

# Customization parameters and their default values.
params:
  placeholder: 0
